android.useAndroidX=true
android.debug.obsoleteApi=true
android.builtInKotlin=false
android.newDsl=false
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx8656M
org.gradle.warning.mode=all
kotlin.mpp.stability.nowarn=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.nonTransitiveRClass=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
