# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Alpha Build to Google Play"
  lane :alpha do
    android_set_version_code(
        gradle_file: "Habitica/build.gradle"
    )
    signed_build
    upload_to_play_store(
        track: "alpha",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    post_to_slack(type: "alpha", url: "https://hooks.slack.com/services/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", channel: "#android")
    post_to_slack(type: "Android", url: "https://hooks.slack.com/services/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", channel: "#new-test-builds")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    android_set_version_code(
        gradle_file: "Habitica/build.gradle"
    )
    signed_build
    upload_to_play_store(
        track: "beta",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    post_to_slack(type: "beta", url: "https://hooks.slack.com/services/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", channel: "#android")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    android_set_version_code(
        gradle_file: "Habitica/build.gradle"
    )
    signed_build
    upload_to_play_store(
        track: "production",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    post_to_slack(type: "production", url: "https://hooks.slack.com/services/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", channel: "#android")
  end

  private_lane :signed_build do
    gradle(task: "clean")
    gradle(
      task: "assembleProd",
      build_type: "Release"
    )
  end

  private_lane :post_to_slack do |options|
    type = options[:type]
    version     = android_get_version_name(gradle_file: "Habitica/build.gradle")
    build       = android_get_version_code(gradle_file: "Habitica/build.gradle")
    url = options[:url]
    channel = options[:channel]

    slack(
      message: ":robot_face: New #{type} build *#{version}* (#{build}) has been submitted :rocket:",
      channel: channel,
      slack_url: url,
      default_payloads: [],
      username: "Google Play Store"
    )

  end
end
