# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Alpha Build to Google Play"
  lane :alpha do
    increment_version_code(
        gradle_file_path: "Habitica/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: "alpha",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    increment_version_code(
        gradle_file_path: "Habitica/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: "beta",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code(
        gradle_file_path: "Habitica/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: "production",
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
  end
end
