-dontwarn com.caverock.androidsvg.SVG
-dontwarn com.caverock.androidsvg.SVGParseException
-dontwarn pl.droidsonroids.gif.GifDrawable
-dontwarn java.lang.invoke.StringConcatFactory
-keep class com.habitrpg.common.habitica.** { *; }
-keep class com.habitrpg.shared.habitica.** { *; }
