name: AV Habitica Release

env:
  # The name of the main module repository
  main_project_module: pt.aguiarvieira.habitica

  # The name of the Play Store
  playstore_name: Habitica

on:

  pull_request:
  merge_group:
  push:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew Habitica:assembleRelease --stacktrace 

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload release APK 
        uses: actions/upload-artifact@v4
        with:
          name: pt.aguiarvieira.habitica.nightly
          path: Habitica/build/outputs/apk/prod/release/Habitica-prod-release.apk

      - name: Deploy Nightly
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          upload_url: https://uploads.github.com/repos/ricardo-duarte-av/habitica-android/releases/201293289/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          release_id: 201293289 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: Habitica/build/outputs/apk/prod/release/Habitica-prod-release.apk # path to archive to upload
          asset_name: habitica.aguiarvieira.pt-release$$.apk # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/vnd.android.package-archive # required by GitHub API
          max_releases: 5 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
